---
title: "Dummy classifier"
author: "Jarkko Toivonen"
date: "11/4/2020"
output: 
  html_document: default
  md_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
source('../../Hb_predictor_container/src/validate_stan_fit.R', chdir=T)
source("economic_effect_functions.R")
```

## Dummy model for females and males on Progesa data

Use the preprocessed validate dataset from random forest runs. Dummy predictor uses -previous_Hb as score for deferral. 


  
```{r}
load("~/FRCBS/interval-sims/rf-train-and-validate-datas.rdata", verbose=TRUE)  # returns train and validate dataframes
load("~/FRCBS/interval-sims/rf-test-data.rdata", verbose=TRUE) # returns test dataframe
```

We use [Logistic function](https://en.wikipedia.org/wiki/Logistic_function) to map previous_Hb values to
the probability range [0, 1].

```{r Logistic regression functions}

logistic <- function(x, k=1, x0=0) 1 / (1 + exp(-k*(x-x0)))

score <- function(previous_Hb, Hb_threshold ) {
  logistic(previous_Hb, k=-0.1, x0=Hb_threshold)
}

make_threshold_conversion_data_frame <- function(Hb_threshold, k) {
  hb <- seq(110, 160, by=2)
  df <- tibble(Hb=hb, 
               Probability = logistic(hb, k=k, x0=Hb_threshold))
  return(df)
}

dummy_predictor <- function(df, Hb_threshold=NULL) { # fake logistic regression
  if (is.null(Hb_threshold)) {    # use -previous_Hb as score
    result <- tibble(Deferred = -df$previous_Hb,
                     obs = df$Hb_deferral)
  } else {                        # use logistic function of previous_Hb as score
    result <- tibble(Deferred = score(df$previous_Hb, Hb_threshold), 
                     obs = df$Hb_deferral)
    
  }
  return(result)
}

logistic_regression <- function(train) {
  glm.fit <- glm(Hb_deferral ~ previous_Hb,
               data = train,
               family = binomial)
  return(glm.fit)  
}

dummy_predictor2 <- function(train, validate) {  # real logistic regression
  glm.fit <- logistic_regression(train)
  print(glm.fit)
  
  glm.probs <- predict(glm.fit,
                      newdata = validate,
                      type = "response")
  
  result <- tibble(score = glm.probs, 
                   original_label = validate$Hb_deferral)

  return(list(result=result, fit=glm.fit))  
}



```

```{r Old logistic function plot to convert between Hb threshold and probability for females, eval=FALSE}
df1 <- make_threshold_conversion_data_frame(125, -1) 
df2 <- make_threshold_conversion_data_frame(125, -0.1)
df <- bind_rows(`k=-1`=df1, `k=-0.1`= df2, .id="k")
df %>% ggplot(aes(x=Hb, y=Probability, color=k)) + geom_point() + scale_y_continuous(breaks=seq(0, 1, by=0.1)) + labs(colour="Logistic function parameter") + ggtitle("Female")
```

```{r  Old logistic function plot to convert between Hb threshold and probability for males, eval=FALSE}
df1 <- make_threshold_conversion_data_frame(135, -1) 
df2 <- make_threshold_conversion_data_frame(135, -0.1)
df <- bind_rows(`k=-1`=df1, `k=-0.1`= df2, .id="k")
df %>% ggplot(aes(x=Hb, y=Probability, color=k)) + geom_point() + scale_y_continuous(breaks=seq(0, 1, by=0.1)) + labs(colour="Logistic function parameter") + ggtitle("Male")
```

```{r}
train_female <- train %>% filter(gender=="Women")
train_male <- train %>% filter(gender=="Men")
validate_female <- validate %>% filter(gender=="Women")
validate_male <- validate %>% filter(gender=="Men")
test_female <- test %>% filter(gender=="Women")
test_male <- test %>% filter(gender=="Men")
```



```{r Fit logistic regression}
use_logistic_regression=TRUE
if (use_logistic_regression) {
  res_female <- dummy_predictor2(train_female, test_female)
  prediction_female <- res_female$result
  fit_female <- res_female$fit
  
  res_male <- dummy_predictor2(train_male, test_male)
  prediction_male <- res_male$result
  fit_male <- res_male$fit
} else {  # Old way was to do it by hand using logistic function
  prediction_female <- dummy_predictor(validate_female, 125)  # or would mean Hb be better centering point than deferral threshold
  prediction_male <- dummy_predictor(validate_male, 135)
}
head(prediction_female)
head(prediction_male)
fit_male
fit_female
```

```{r}
if (FALSE) {
  save(prediction_female, file="~/FRCBS/interval-sims/progesa-validate-female-dummy2.rdata")
  save(prediction_male, file="~/FRCBS/interval-sims/progesa-validate-male-dummy2.rdata")
}
```

```{r Compute performance measures}
#dummy_result <- suppressMessages(process_all_data(dummy2_ids, replicates=100))
dummy_result <- suppressMessages(process_all_data(dummy_ids))
```

```{r Show the result table}
df <- dummy_result %>% 
  pivot_wider(names_from=c("variable", "type"), values_from=value, names_glue="{variable} {type}")
names(df) <- str_remove(names(df), " value$")
df <- df %>%
  select("Id", "F1", "F1 low", "F1 high", "threshold6", "threshold12", "E6", "E6 low", "E6 high", "E12", "E12 low", "E12 high")

kable(df)
```

```{r}
data <- tibble(previous_Hb = seq(100, 200))
data[["male"]] <- predict(fit_male, newdata=data, type="response")
data[["female"]] <- predict(fit_female, newdata=data, type="response")
data2 <- data %>% pivot_longer(cols=c(male, female), names_to="Sex", values_to="Probability")
#data2

mt <- df %>% filter(Id=="progesa-male-dummy") %>% select(threshold6, threshold12) %>% as.numeric()   # male thresholds
ft <- df %>% filter(Id=="progesa-female-dummy") %>% select(threshold6, threshold12) %>% as.numeric() # female thresholds
mhb <- approx(x = data$male,   y = data$previous_Hb, xout=mt)$y                                          # corresponding male hemoglobins
fhb <- approx(x = data$female, y = data$previous_Hb, xout=ft)$y                                          # corresponding female hemoglobins
threshold_data <- tibble(previous_Hb = c(mhb, fhb), Probability=c(mt, ft), text=c("t6", "t12", "t6", "t12"), Sex=c("male", "male", "female", "female"))
kable(threshold_data)

g <- data2 %>% ggplot(aes(x=previous_Hb, y=Probability, color=Sex)) + 
  geom_line() +
  geom_vline(data=threshold_data, mapping=aes(xintercept=previous_Hb, colour=Sex)) +
  geom_text(data=threshold_data, mapping=aes(x=previous_Hb, label=text), y=0.1, show.legend=FALSE, nudge_x=2.5)
g
```


```{r}
roc_female <- roc_wrapper(prediction_female)
pr_female <- pr_wrapper(prediction_female)
```

```{r}
roc_male <- roc_wrapper(prediction_male)
pr_male <- pr_wrapper(prediction_male)
```

```{r}
roc_female
pr_female$pr_plot
roc_male
pr_male$pr_plot
```

Compute the effects of applying baseline model. This needs still some cleanup.


```{r}
result_male <- res_male$result %>% mutate(prediction=as.factor(ifelse(Deferred>0.36, "Deferred", "Accepted")))
result_female <- res_female$result %>% mutate(prediction=as.factor(ifelse(Deferred>0.64, "Deferred", "Accepted")))
```

```{r}
summary(result_male)
```

```{r}
summary(result_female)
```

```{r}
nm <- nrow(result_male)
nf <- nrow(result_female)
md <- sum(result_male$obs=="Deferred")
fd <- sum(result_female$obs=="Deferred")
cat(sprintf("Men deferred %i (%.2f%%)\n", md, md/nm*100))
cat(sprintf("Women deferred %i (%.2f%%)\n", fd, fd/nf*100))

md2 <- sum(result_male$obs=="Deferred" & result_male$prediction=="Accepted")
fd2 <- sum(result_female$obs=="Deferred" & result_female$prediction=="Accepted")
cat(sprintf("Men deferred %i (%.2f%%)\n", md2, md2/nm*100))
cat(sprintf("Women deferred %i (%.2f%%)\n", fd2, fd2/nf*100))

```
```{r}
mextension <- sum(result_male$prediction=="Deferred")
fextension <- sum(result_female$prediction=="Deferred")
cat(sprintf("Men extended for 6 months %i (%.2f%%)\n", mextension, mextension/nm*100))
cat(sprintf("Women extended for 6 months %i (%.2f%%)\n", fextension, fextension/nf*100))
```



