---
title: "Untitled"
author: "Jarkko Toivonen"
date: "8/24/2021"
output: 
  md_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("economic_effect_functions.R")
source("article_figures_functions.R")
library(knitr)
library(tidyverse)
save_figs = TRUE
save_tables = FALSE
dir <- "~/FRCBS/interval-sims/src/new_cost_parameters"
fig_path <- dir
table_path <- dir
all_results_filename <- sprintf("%s/raw-data-2021-08-27.tsv", dir)
compute=FALSE
```

## R Markdown

Try the economic effect calculations with the new parameters values.

```{r}
new_fixed_parameters <- list(Pm=2.287, Pd=19.96, F=1, Fn=0.1066, rloss=0)
#new_fixed_parameters <- list(Pm=2.287, Pd=18.08, F=1, Fn=0.1066, rloss=0)

new_parameters <- c(data_parameters, new_fixed_parameters)
if (compute) {
  all_results <- process_all_data(all_ids, parameters=new_parameters)
  write_tsv(all_results, file=all_results_filename)
} else {
  all_results <- read_tsv(file=all_results_filename)  
}

```
The cost surface below is for the random forest on eProgesa data. 

```{r Cost surface}
g <- draw_surface(results=all_results %>% filter(Id == "progesa-both-rf"), cost_function=do.call(cost_func_factory, new_parameters[c("Pm", "Pd", "F", "Fn", "rloss", "d")]))
if (save_figs) {
  filename <- sprintf("%s/cme_cost_surface_werr.pdf", fig_path)
  ggsave(filename=filename,  width = 180,  height = 120, units="mm", dpi=600, scale=1.0, device=cairo_pdf)
}
g
```

```{r Performance plot}
# finngen-male-dlmm  E12 a12 and f1 values are for some reason NA
#df <- all_results %>% 
#  replace_na(list(value=0))  

res <- create_performance_forest_plot(all_results)
g <- res$g
df <- res$df
if (save_figs) {
  filename <- sprintf("%s/performance-forest-plot.pdf", fig_path)
  ggsave(filename=filename, #  title="Performance forest plot", 
         plot=g, dpi=600, units="mm", width=180, device=cairo_pdf)
}
g
```
